
export const ON_SEARCH_TEXT = "ON_SEARCH_TEXT"
export const ADD_NEW_ROW = "ADD_NEW_ROW"
export const UPDATE_COLUMN_CONTENT = "UPDATE_COLUMN_CONTENT"
export const UPDATE_COLUMN_STATUS = "UPDATE_COLUMN_STATUS"
export const ON_DELETE_ROW = "ON_DELETE_ROW"
export const UPDATE_ROWS_ORDER = "UPDATE_ROWS_ORDER"
export const ON_CLICK_ORDER = "ON_CLICK_ORDER"
